FROM python:3.12

WORKDIR /tmp

# install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt


# set environment variables
# (these get re-set by the compose, but they're here for reference)
ENV DB_USER=postgres
ENV DB_PASSWORD=postgres
ENV DB_HOST=0.0.0.0
ENV DB_PORT=5432
ENV ALLOWED_HOSTS=0.0.0.0

# expose port
EXPOSE 8000

WORKDIR /app

# run script
CMD ["/bin/bash", "script.sh"]
