FROM python:3.12

WORKDIR /tmp

# install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# expose port
EXPOSE 8000

WORKDIR /app

# migrate and then have the development server
CMD ["sh", "-c", "python manage.py makemigrations \
    && python manage.py migrate \
    && python manage.py runserver 0.0.0.0:8000"]