name: Setup
description: "Setup python and install dependencies"

inputs:
  python-version:
    description: "Version of python to setup"
    required: true
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
